# Local Dev Build
FROM python:3.12-slim-bookworm
LABEL org.opencontainers.image.authors="Publicis Sapient Engineering"

WORKDIR /app

# Install components, upgrade machine & add supervisor
RUN apt-get update
RUN apt-get install -y procps git curl wget nano gettext gettext-base unzip libpq-dev default-libmysqlclient-dev mysql-common pkg-config gcc micro htop
RUN pip3 install --upgrade pip
RUN pip3 install supervisor poetry
RUN mkdir -p /var/log/supervisor

# Upgrade all
RUN apt-get update && apt-get dist-upgrade -y

# Install requirements
ADD poetry.lock /app
ADD pyproject.toml /app
RUN poetry install

# Entrypoint (migrate)
ENTRYPOINT ["./entrypoint-dev.sh"]
