"""DescriptionProvider port.

Domain-side contract for retrieving placeholder-resolved descriptive content
about library classes and their parameters. Methods return strings ready for
the consumer (HTML or plain text depending on the adapter mode), or ``None``
when no content is available. Callers never see raw ``{kind:target}`` tokens.
"""
from typing import Protocol


class DescriptionProvider(Protocol):
    def class_description(self, class_name: str) -> str | None: ...
    def class_disambiguation(self, class_name: str) -> str | None: ...
    def class_pitfalls(self, class_name: str) -> str | None: ...
    def class_interactions(self, class_name: str) -> str | None: ...
    def class_doc_link(self, class_name: str) -> str: ...
    def param_description(self, class_name: str, param: str) -> str | None: ...
    def field_tooltip(self, class_name: str, param: str) -> str | None: ...
    def interface_only_tooltip(self, param: str) -> str | None: ...
    def calc_description(self, class_name: str, attr: str) -> str | None: ...
    def param_interaction(self, class_name: str, param: str) -> str | None: ...
