from django.urls import path

import model_builder.adapters.views.views_addition
import model_builder.adapters.views.views_deletion
import model_builder.adapters.views.views_dict_mutation
import model_builder.adapters.views.views_edition
from .adapters.views import views
from .adapters.views import sankey_views

urlpatterns = [
    path("", views.model_builder_main, name="model-builder"),
    path("<reboot>", views.model_builder_main, name="model-builder"),
    path("open-create-object-panel/<object_type>/",
         model_builder.adapters.views.views_addition.open_create_object_panel, name="open-add-new-object-panel"),
    path("add-object/<object_type>/",
         model_builder.adapters.views.views_addition.add_object, name="add-new-object"),
    path("open-edit-object-panel/<object_id>/", model_builder.adapters.views.views_edition.open_edit_object_panel,
         name="open-edit-object-panel"),
    path("edit-object/<object_id>/", model_builder.adapters.views.views_edition.edit_object, name="edit-object"),
    path("open-link-existing-panel/<parent_id>/<child_type_str>/",
         model_builder.adapters.views.views_edition.open_link_existing_panel,
         name="open-link-existing-panel"),
    path("update-dict-count/<str:parent_id>/<str:key_id>/",
         model_builder.adapters.views.views_dict_mutation.update_dict_count,
         name="update-dict-count"),
    path("unlink-dict-entry/<str:parent_id>/<str:key_id>/",
         model_builder.adapters.views.views_dict_mutation.unlink_dict_entry,
         name="unlink-dict-entry"),
    path("link-dict-entry/<str:key_id>/",
         model_builder.adapters.views.views_dict_mutation.link_dict_entry,
         name="link-dict-entry"),
    path("delete-object/<object_id>/", model_builder.adapters.views.views_deletion.delete_object, name="delete-object"),
    path("ask-delete-object/<object_id>/", model_builder.adapters.views.views_deletion.ask_delete_object, name="ask-delete-object"),
    path("download-json/", views.download_json, name="download-json"),
    path("result-chart/", views.result_chart, name="result-chart"),
    path("open-import-json-panel/", views.open_import_json_panel, name="open-import-json-panel"),
    path("upload-json/", views.upload_json, name="upload-json"),
    path("display-calculus-graph/<efootprint_id>/<attr_name>/", model_builder.adapters.views.views.display_calculus_graph,
         name="display-calculus-graph"),
    path("display-calculus-graph/<efootprint_id>/<attr_name>/<id_of_key_in_dict>", model_builder.adapters.views.views.display_calculus_graph,
         name="display-calculus-graph-from-dict"),
    path("graph/<cache_key>", model_builder.adapters.views.views.get_calculus_graph, name="get-graph"),
    path("download-sources/", views.download_sources, name="download-sources"),
    path("source-table/", views.source_table, name="source-table"),
    path("open-panel-system-name/", model_builder.adapters.views.views_edition.open_panel_system_name,
         name="open-panel-system-name"),
    path("save-system-name/", model_builder.adapters.views.views_edition.save_system_name, name="save-system-name"),
    path("get_explainable_hourly_quantity_chart_and_explanation/<efootprint_id>/<attr_name>/",
         model_builder.adapters.views.views.get_explainable_hourly_quantity_chart_and_explanation,
         name="get_explainable_hourly_quantity_chart_and_explanation"),
    path("get_explainable_hourly_quantity_chart_and_explanation/<efootprint_id>/<attr_name>/<id_of_key_in_dict>",
         model_builder.adapters.views.views.get_explainable_hourly_quantity_chart_and_explanation,
         name="get_explainable_hourly_quantity_chart_and_explanation_from_dict"),
    path("get_explainable_recurrent_quantity_chart_and_explanation/<efootprint_id>/<attr_name>/",
         model_builder.adapters.views.views.get_explainable_recurrent_quantity_chart_and_explanation,
         name="get_explainable_recurrent_quantity_chart_and_explanation"),
    path("get_calculated_attribute_explanation/<efootprint_id>/<attr_name>/",
         model_builder.adapters.views.views.get_calculated_attribute_explanation,
         name="get_calculated_attribute_explanation"),
    path("get_calculated_attribute_explanation/<efootprint_id>/<attr_name>/<id_of_key_in_dict>",
         model_builder.adapters.views.views.get_calculated_attribute_explanation,
         name="get_calculated_attribute_explanation_from_dict"),
    path("get_eco_logits_calculated_attribute_explanation/<efootprint_id>/<attr_name>/",
         model_builder.adapters.views.views.get_eco_logits_calculated_attribute_explanation,
         name="get_eco_logits_calculated_attribute_explanation"),
    path("sankey-diagram/", sankey_views.sankey_diagram, name="sankey-diagram"),
    path("sankey-cards/", sankey_views.sankey_cards, name="sankey-cards"),
    path("sankey-delete-card/", sankey_views.sankey_delete_card, name="sankey-delete-card"),
    path("sankey-form/", sankey_views.sankey_form, name="sankey-form"),
]
