global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

accessLog: {}
ping: {}

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dyn.yml
    watch: true

log:
  level: INFO
  format: common